services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npm run migration:run && npm run start:dev"
  db:
    image: mysql:8
    volumes:
      - ./mysql_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my-nestjs-test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=superpass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-psuperpass"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s